id: IAC971551
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T13:46:13+00:00'
last_modified: '2022-06-07T12:03:50.178519+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20189
  title: དྲག་པོ་ཡེ་ཤེས་རབ་འབར་གྱི་བསྙེན་ཡིག་དམ་པའི་ཞལ་ལུང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0888:
      image_group_id: I8LS20191
      title: Volume 1 of drag po ye shes rab 'bar gyi bsnyen yig dam pa'i zhal lung
        /
      total_pages: 70
      order: 1
      base_file: 0888.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
